- name: restart mysql
  service: name=mysql state=restarted

- name: start nginx
  service: name=nginx state=started 

- name: restart nginx
  service: name=nginx state=restarted

- name: start php5-fpm
  service: name=php-fpm state=started
